### ISSUE TITLE
Stacktrace from a smooshy run

### ISSUE THREAD

**Issue by jorourke** [josegonzalez/python-smooshy#1]
```
Smooshing ./uploads/2013/07/MG_0915.jpg...
  FAIL: Smooshing error. Backup restored.
Traceback (most recent call last):
  File "/home/bitnami/.virtualenvs/default/bin/smooshy", line 15, in <module>
    smooshy.smoosher.recursive_smoosher(args)
  File "/home/bitnami/.virtualenvs/default/local/lib/python2.7/site-packages/smooshy/smoosher.py", line 154, in recursive_smoosher
    result = Smoosher(os.path.join(base, name)).smoosh()
  File "/home/bitnami/.virtualenvs/default/local/lib/python2.7/site-packages/smooshy/smoosher.py", line 108, in smoosh
    smooshed = self.get_smooshed()
  File "/home/bitnami/.virtualenvs/default/local/lib/python2.7/site-packages/smooshy/smoosher.py", line 81, in get_smooshed
    raise SmushItException(response['error'])
smooshy.smoosher.SmushItException: No files were uploaded
```

Is it possible to run the tool in a mode which gracefully handles exceptions?

**Comment by josegonzalez** [comment]
What would you want it to do?

**Comment by jorourke** [comment]
just keep smooshing other files, but catch the exception and report it, and leave the file that caused the crash as it was.

**Comment by josegonzalez** [comment]
Would you mind making a pull request for the binary?

**Comment by josegonzalez** [comment]
Closing as yahoo shutdown smush.it.
